version: 2.1
jobs:
  build:
    docker:
      - image: cimg/php:8.1.27-node
    steps:
      - checkout
      - run:
          name: Install Composer dependencies
          command: cd src && composer install --no-interaction --prefer-dist
      - restore_cache:
          key: composer-v1-{{ checksum "src/composer.lock" }}
      - save_cache:
          key: composer-v1-{{ checksum "src/composer.lock" }}
          paths:
            - src/vendor
      - run:
          name: php test
          command: cd src && vendor/bin/phpunit
